//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ad_posting_eproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_order()
        {
            this.tbl_invoice = new HashSet<tbl_invoice>();
        }
    
        public int order_id { get; set; }
        public Nullable<double> order_amount { get; set; }
        public Nullable<int> order_quantity { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<int> ad_id_fk { get; set; }
        public Nullable<int> cat_id_fk { get; set; }
        public Nullable<int> u_id_fk { get; set; }
        public Nullable<int> pro_id_fk { get; set; }
    
        public virtual tbl_admin tbl_admin { get; set; }
        public virtual tbl_cateogry tbl_cateogry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_invoice> tbl_invoice { get; set; }
        public virtual tbl_product tbl_product { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
